### ISSUE TITLE
Current Event gets archived on day of event

### ISSUE THREAD

**Issue by madmurdock** [Codercamp/codercamp.github.io#53]
Should archive day after?

**Comment by mirhagk** [comment]
Okay found the problematic code, 

~~~
var eventDate = new Date($(event).data('date'));
eventDate.setHours(0,0,0,0);
if (eventDate < today){
     $(event).hide();
}
~~~

is supposed to get the event date and clear out the time part. Unfortunately `$(event).data('date')` is UTC so `2017-01-11 00:00:00 +0000`. `new Date()` thinks it's being clever and converts it to your timezone. Since UTC is in the future it converts it to `2017-01-10 19:00` and that is yesterday.

A fix here would be to just use ISO strings and compare the first slices. ie `$(event).data('date').slice(0,10)` and `today.toISOString().slice(0,10)`.

Just going to test it locally then I'll make this change

**Comment by mirhagk** [comment]
Just a note, if you're trying to reproduce this locally you won't be able to. The date comes through as the servers timezone, and locally that's going to match your browsers timezone. But github pages are served on a UTC timezone'd server

**Comment by rprouse** [comment]
We could just do it a bit hacky and compare to tomorrow instead of today. Does it really matter if events stay up an extra 12 to 24 hours?

**Comment by mirhagk** [comment]
I've fixed it now, but it might be worth discussing keeping it up an extra amount of time anyways
